[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd website/client && npm install"]

[phases.build]
cmds = ["cd website/client && npm run build"]

[start]
cmd = "cd website/client && node .output/server/index.mjs"
